steps:
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['ci']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      ['build','-t','us-east5-docker.pkg.dev/bodigi-477210/bodigi-images/BoDiGi:$SHORT_SHA','-t','us-east5-docker.pkg.dev/bodigi-477210/bodigi-images/BoDiGi:latest','.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push','us-east5-docker.pkg.dev/bodigi-477210/bodigi-images/BoDiGi:$SHORT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push','us-east5-docker.pkg.dev/bodigi-477210/bodigi-images/BoDiGi:latest']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      ['run','deploy','BoDiGi','--image=us-east5-docker.pkg.dev/bodigi-477210/bodigi-images/BoDiGi:$SHORT_SHA','--region=us-east5','--platform=managed','--allow-unauthenticated','--port=8080']
images:
  - 'us-east5-docker.pkg.dev/bodigi-477210/bodigi-images/BoDiGi:$SHORT_SHA'
